### ISSUE TITLE
Release 1.1.1 appears to have broken graypy

### ISSUE THREAD

**Issue by Canuteson** [severb/graypy#103]
Release 1.1.1 an hour ago.

>>> from graypy import GELFHandler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'GELFHandler'

Is the 1.x release not intended to be backwards compatible with 0.3.x releases?

**Comment by nklapste** [comment]
Yes 1.X.X is backwards breaking as majority of Handlers have been renamed and restructured.

**Comment by nklapste** [comment]
Noted that graypy version 1.X.X+ is backwards breaking from graypy version 0.3.X+.
