### ISSUE TITLE
simply not working

### ISSUE THREAD

**Issue by ohadpartuck** [severb/graypy#47]
```
import logging
import graypy

my_logger = logging.getLogger('test_logger')
my_logger.setLevel(logging.DEBUG)

handler = graypy.GELFHandler('my_graylog_server', 12201)
my_logger.addHandler(handler)

my_adapter = logging.LoggerAdapter(logging.getLogger('test_logger'),
                                   { 'username': 'John' })

my_adapter.debug('Hello Graylog2 from John.')
```

is not working 

I think the issue is the url that should send to `/gelf`
because when I curl from the terminal to my graylog server , it works
```
 curl -XPOST http://my_graylog_server:12201/gelf -p0 -d '{"short_message":"Hello there", "host":"example1111.org", "facility":"test", "_foo":"bar"}'
```

**Comment by vladimirtsyupko** [comment]
IIUC instead of sending HTTP request you should send an UDP message like this
  echo -e '{"version": "1.1","host":"example.org","short_message":"Short message","full_message":"Backtrace here\n\nmore stuff","level":1,"_user_id":9001,"_some_info":"foo","_some_env_var":"bar"}\0' | nc -w 1 -u 127.0.0.1 12201

**Comment by ganeshm25** [comment]
MY setup is as follows:

Under the same VPC.

Amazon ec2 instance : Graylog server deployed over nginx. 

Amazon ec2 : Django Server instance installed.


1. I setup django server with graypy. COnfigured Django Settings to use GELFHandler for DjangoRequests.

2. Setup inputs of type GELD UDP and GELF TCP on gray-interface.

3. restarted all servers.

4. attempted to use both IP address and Amazon ec2 instance address when providing LOGGER gray [HOSTNAME].


Any help as to why the config is unable to receive Log messages , will be appreciated ?

**Comment by asyazwan** [comment]
@ganeshm25 Similar setup as me. I realized that I need to setup GELF UDP instead of GELF HTTP. Then it worked, following the example code. Make sure port 12201 is permitted inbound in your VPC security group.

**Comment by zheli** [comment]
This package will not work with TCP because the handler is based on DatagramHandler and it only send messages over UDP sockets.
