### ISSUE TITLE
Appending extra fields directly during initialization of GELFHandler

### ISSUE THREAD

**Issue by davidchua** [severb/graypy#61]
Hi guys,

Thanks for the package! Really awesome stuff.

I'd like to ask if there's a way to append extra fields to each log request from the initialization of GELFHandler itself?

I'm running a `tornado` app and I'm able to log everything correctly with:

```
handler = graypy.GELFHandler('ip, 12201, localname="service")
logging.getLogger("tornado.access").addHandler(handler)
logging.getLogger("tornado.application").addHandler(handler)
logging.getLogger("tornado.general").addHandler(handler)
```

I'd like to be able to append some extra fields onto every log that uses the GELFHandler. Looking at the docs, it seems like the way to do it is via LoggerAdapter but that wouldn't work in tornado's case as it uses the logger("tornado.access") by default etc.

**Comment by severb** [comment]
Sorry for a late reply. I don't think there's good support for your specific case; have you managed to get it working?
