### ISSUE TITLE
GELFRabbitHandler and missing Queue/Binding

### ISSUE THREAD

**Issue by claytondaley** [severb/graypy#64]
I was having trouble with the GELFRabbitHandler example because the queue and exchange weren't bound.  I eventually realized this because `rabbitmqadmin` provides the feedback "Message published but NOT routed".  GELFRabbitHandler provides no feedback about this situation.  I checked and a comparable situation exists if the exchange is missing.

Are there any acceptable options to remedy this situation?  I work in a regulated industry (healthcare).  I'm using the GELFRabbitHandler because I have to maintain the integrity of the logs (can't drop UDP packets).  If GELFRabbitHandler isn't working, I **really** need to know so I can stop serving content.

I realize errors while logging are a bit of a catch-22 since the log _is_ the standard place to send them.  Is there an appropriate (alternative) way of escalating an issue like this?  For example, would you be open to a PR that adds a "strict" mode that:
- Attempts to send a message
- If it gets one of the two severe errors ("Not found" or "NOT routed"), attempts to create the infrastructure
- If it cannot create the infrastructure (for example, due to permissions), raises an exception (with the intent that the server produces a 500 error)

If you prefer, I could make the 3rd bullet a callback to make it easy to produce custom behaviors (e.g. email the admins).

**Comment by severb** [comment]
Sorry for a late reply. Your use-case seems very specific, and I don't think this handling belongs in a general purpose library like this. Please feel free to fork the code and adapt it to your needs or build on top of what it's in here already.

**Comment by claytondaley** [comment]
I realize that a lot of people don't need reliable logging.  However, there are plenty of regulated industries where it would be a best practice.  At minimum, it seems like it should be possible to raise an exception if the logging infrastructure isn't working.  That's a common kind of option for a library.
