### ISSUE TITLE
Versioning of Graypy

### ISSUE THREAD

**Issue by tusharmakkar08** [severb/graypy#67]
Hey @severb 

In Pypi server the live version of Graypy is [0.2.14](https://pypi.python.org/pypi/graypy/0.2.14) while in the setup.py the version mentioned is [0.2.13](https://github.com/severb/graypy/blob/master/setup.py#L8). What's the reason behind such discrepancy? Can we please get it updated? Also, it would be great if we can maintain tags for the same. 

Thanks.

**Comment by severb** [comment]
I think I just forgot to push the `setup.py` change and to push the new tag when I did the last release. The `0.2.14` version contains the code from 10f97aa. I'll push a branch for this version and tag it to fix the mess.

**Comment by tusharmakkar08** [comment]
Cool 👍 
Close this issue when done.

**Comment by severb** [comment]
I pushed a tag for `0.2.14`. It points to a branch because I had to retroactively apply the `setup.py` version change. This shouldn't be a big deal, we just have to remember to bump the version twice for the next release, to `0.2.15`.
