### ISSUE TITLE
Adding Travis Support 

### ISSUE THREAD

**Issue by tusharmakkar08** [severb/graypy#68]
Hey @severb 

Since `graypy` is an evolving project, I think it would be great to add automated tests/CI support using Travis. I can help in setting up that. Let me know if you are interested.

Thanks.

**Comment by severb** [comment]
I think this is a fantastic idea. I don't have time to do it myself but if you're serious about it I would gladly accept pull requests.

**Comment by tusharmakkar08** [comment]
Cool. I will work on this and create a PR :)

**Comment by tusharmakkar08** [comment]
Hey @severb, Can you please enable the travis over here https://travis-ci.org/severb ?

**Comment by severb** [comment]
Yup, I'll do it now.

**Comment by tusharmakkar08** [comment]
Done
