### ISSUE TITLE
version 0.2.14 on pypi is not 0.2.14

### ISSUE THREAD

**Issue by Anthchirp** [severb/graypy#78]
The version 0.2.14 on https://pypi.python.org/pypi/graypy is not identical to the 0.2.14 release file on Github.

The pypi release matches revision 10f97aa633ca32c2b2c34c5f90d0d0ebcd010da1 of the 11th of July, which was the first merge after 0.2.13.

**Comment by tusharmakkar08** [comment]
@severb: Please look into this.

**Comment by severb** [comment]
I think it's true, the versions don't match. Instead of going back and fixing it, I just released version `0.3`.

**Comment by Anthchirp** [comment]
👍  works for me
